services:
  - type: web
    name: neuralis-web
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VERCEL
        value: ""
      - key: SESSION_SECRET
        generateValue: true
      - key: FORMSPREE_ENDPOINT
        sync: false
    autoDeploy: true
